apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
  labels:
    name: springboot
spec:
  replicas: 3
  template:
    metadata:
      name: springboot
      labels:
        name: springboot
        version: blue
    spec:
      containers:
      - image: dockergunn/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080      

