apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
        version: v1
    spec:
      containers:
      - image: dockergunn/myapp:v1
        name: myapp
        ports:
        - name: myapp
          containerPort: 8080      

