---
apiVersion: v1
kind: Pod
metadata:
  name: myapache
  labels:
    team: devops
spec:
  containers:
    - name: myapachecontainer
      image: httpd
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapacheservice
spec:
  selector:
    team: devops
  ports:
    - port: 80
  type: NodePort 
