apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
  labels:
    name: springboot
spec:
  replicas: 1
  template:
    metadata:
      name: springboot
      labels:
        name: springboot
        version: green
    spec:
      containers:
      - image: dockergunn/nginx:1.11
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
